version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11rc2

    working_directory: ~/transfer-info
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get .

      - run: go test -v -count=1 .

      - run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o transfer-info
 
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - add_ssh_keys:
          fingerprints:
            - "74:4c:1f:71:95:6a:f0:fc:8d:c7:85:4a:27:c1:3e:90"

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no transfer-info@transfer-info.euro2.ee /bin/mkdir /opt/transfer-info/builds/"${CIRCLE_BUILD_NUM}"
              scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r  ~/transfer-info/transfer-info transfer-info@transfer-info.euro2.ee:/opt/transfer-info/builds/"${CIRCLE_BUILD_NUM}"/
              echo "cd /opt/transfer-info && /bin/ln -sf builds/"${CIRCLE_BUILD_NUM}"/transfer-info transfer-info-latest" | ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no transfer-info@transfer-info.euro2.ee
              ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no transfer-info@transfer-info.euro2.ee sudo /bin/systemctl restart transfer-info
            fi
